import json
import unittest
from pathlib import Path


class BrowserExtensionAssetsTestCase(unittest.TestCase):
    def test_manifest_references_required_files(self) -> None:
        project_root = Path(__file__).resolve().parents[2]
        extension_root = project_root / 'frontend' / 'extension'

        manifest = json.loads((extension_root / 'manifest.json').read_text(encoding='utf-8'))

        self.assertEqual(manifest['manifest_version'], 3)
        self.assertEqual(manifest['background']['service_worker'], 'background.js')
        self.assertEqual(manifest['action']['default_title'], '飞猪运营助手')
        self.assertEqual(manifest['action']['default_popup'], 'popup.html')
        self.assertEqual(manifest['options_page'], 'options.html')
        self.assertIn('tabs', manifest['permissions'])
        self.assertIn('notifications', manifest['permissions'])
        self.assertIn("frame-src 'self' http://api.aihuawise.com", manifest['content_security_policy']['extension_pages'])

        content_scripts = manifest['content_scripts']
        self.assertTrue(content_scripts)
        self.assertEqual(
            content_scripts[0]['js'],
            [
                'content/page-context.js',
                'content/result-view.js',
                'content.js',
            ],
        )

        for file_name in [
            'background.js',
            'content.js',
            'popup-shell.html',
            'popup-shell.js',
            'popup.html',
            'popup.js',
            'options.html',
            'options.js',
            'README.md',
            'notification-icon.svg',
            'content/page-context.js',
            'content/result-view.js',
        ]:
            self.assertTrue((extension_root / file_name).exists(), file_name)

    def test_extension_contains_workflow_first_popup(self) -> None:
        project_root = Path(__file__).resolve().parents[2]
        extension_root = project_root / 'frontend' / 'extension'
        manifest = json.loads((extension_root / 'manifest.json').read_text(encoding='utf-8'))
        content_js = (extension_root / 'content.js').read_text(encoding='utf-8')
        popup_html = (extension_root / 'popup.html').read_text(encoding='utf-8')
        popup_shell_html = (extension_root / 'popup-shell.html').read_text(encoding='utf-8')
        popup_shell_js = (extension_root / 'popup-shell.js').read_text(encoding='utf-8')
        popup_js = (extension_root / 'popup.js').read_text(encoding='utf-8')
        background_js = (extension_root / 'background.js').read_text(encoding='utf-8')
        options_html = (extension_root / 'options.html').read_text(encoding='utf-8')
        options_js = (extension_root / 'options.js').read_text(encoding='utf-8')
        page_context_js = (extension_root / 'content/page-context.js').read_text(encoding='utf-8')
        backend_root = project_root / 'backend'
        backend_main = (backend_root / 'app' / 'main.py').read_text(encoding='utf-8')
        cloud_ui_root = backend_root / 'app' / 'static' / 'ops-assistant'
        cloud_ui_html = (cloud_ui_root / 'index.html').read_text(encoding='utf-8')
        cloud_ui_js = (cloud_ui_root / 'app.js').read_text(encoding='utf-8')

        self.assertIn('GET_PAGE_CONTEXT', content_js)
        self.assertIn('OPEN_PANEL', content_js)
        self.assertIn('CLOUD_ASSISTANT_ORIGIN = "http://api.aihuawise.com"', content_js)
        self.assertIn('CLOUD_ASSISTANT_URL = `${CLOUD_ASSISTANT_ORIGIN}/ops-assistant`', content_js)
        self.assertIn('CLOUD_PROTOCOL_VERSION = "fliggy-ops-cloud-ui/v1"', content_js)
        self.assertIn('FLIGGY_OPS_CLOUD_REQUEST', content_js)
        self.assertIn('FLIGGY_OPS_CLOUD_RESPONSE', content_js)
        self.assertIn('action === "plugin.runtime"', content_js)
        self.assertIn('action === "page.getSnapshot"', content_js)
        self.assertIn('sandbox="allow-scripts allow-forms allow-same-origin allow-popups allow-downloads"', content_js)
        self.assertIn('"http://api.aihuawise.com/*"', json.dumps(manifest, ensure_ascii=False))
        self.assertIn('"default_popup": "popup.html"', json.dumps(manifest, ensure_ascii=False))
        self.assertIn('"popup.js"', json.dumps(manifest, ensure_ascii=False))
        self.assertIn('"content/result-view.js"', json.dumps(manifest, ensure_ascii=False))
        self.assertIn('chrome.runtime.getURL("popup.html")', content_js)
        self.assertIn('url.searchParams.set("embedded", "1")', content_js)
        self.assertIn('CLOUD_ASSISTANT_URL = `${CLOUD_ASSISTANT_ORIGIN}/ops-assistant`', popup_shell_js)
        self.assertIn('CLOUD_PROTOCOL_VERSION = "fliggy-ops-cloud-ui/v1"', popup_shell_js)
        self.assertIn('host", "extension-popup"', popup_shell_js)
        self.assertIn('FLIGGY_OPS_CLOUD_REQUEST', popup_shell_js)
        self.assertIn('FLIGGY_OPS_CLOUD_RESPONSE', popup_shell_js)
        self.assertIn('action === "plugin.runtime"', popup_shell_js)
        self.assertIn('action === "page.getSnapshot"', popup_shell_js)
        self.assertIn('action === "panel.open"', popup_shell_js)
        self.assertIn('Unsupported cloud runtime message type', popup_shell_js)
        self.assertIn('iframe', popup_shell_html)
        self.assertIn('id="cloud-frame"', popup_shell_html)
        self.assertIn('本地备用', popup_shell_html)
        self.assertIn('sandbox="allow-scripts allow-forms allow-same-origin allow-popups allow-downloads"', popup_shell_html)
        self.assertIn("@app.route('/ops-assistant'", backend_main)
        self.assertIn('Cache-Control', backend_main)
        self.assertIn('FLIGGY_OPS_CLOUD_REQUEST', cloud_ui_js)
        self.assertIn('FLIGGY_OPS_CLOUD_RESPONSE', cloud_ui_js)
        self.assertIn('plugin.runtime', cloud_ui_js)
        self.assertIn('page.getContext', cloud_ui_js)
        self.assertIn('COMPETITOR_ROOM_PRICES_TABS', cloud_ui_js)
        self.assertIn('COMPETITOR_WORKFLOW_PREVIEW', cloud_ui_js)
        self.assertIn('id="room-prices-btn"', cloud_ui_html)
        self.assertIn('id="merchant-preview-btn"', cloud_ui_html)
        self.assertIn('data-action="room-prices"', content_js)
        self.assertIn('账号登录、当前页面和当前配置已迁到设置页。', content_js)
        self.assertIn('data-basic-section="room-prices"', content_js)
        self.assertIn('data-basic-section="advice"', content_js)
        self.assertIn('data-basic-section="quick-actions"', content_js)
        self.assertIn('width: 400px', content_js)
        self.assertIn('height: 780px', content_js)
        self.assertIn('max-height: calc(100vh - 40px)', content_js)
        self.assertIn('fliggy-ops-workspace-result-card', content_js)
        self.assertIn('data-result-page="workspace"', content_js)
        self.assertIn('fliggy-ops-subnav-button', content_js)
        self.assertIn('data-action="refresh-room-config"', content_js)
        self.assertIn('data-action="merchant-pricing-load"', content_js)
        self.assertIn('data-action="merchant-uniform-submit"', content_js)
        self.assertIn('merchantPlatformLinks', content_js)
        self.assertIn('merchantPlatformLinks', background_js)
        self.assertIn('仅适用于你已经线下确认所有可提交房型都要使用同一目标价的场景', content_js)
        self.assertIn('商家价格页 URL', content_js)
        self.assertIn('商家价格页链接: ', content_js)
        self.assertIn('data-action="merchant-pricing-preview"', content_js)
        self.assertIn('data-action="merchant-pricing-fill"', content_js)
        self.assertIn('data-action="merchant-pricing-submit"', content_js)
        self.assertIn('data-action="competitor-trend-refresh"', content_js)
        self.assertIn('fliggy-ops-trend-series', content_js)
        self.assertIn('fliggy-ops-competitor-trend-box', content_js)
        self.assertIn('COMPETITOR_PRICE_TREND_SUMMARY', content_js)
        self.assertIn('renderCompetitorTrendPanel', content_js)
        self.assertIn('renderCompetitorTrendSeriesDetails', content_js)
        self.assertIn('曲线明细：按主流房型 + 竞对酒店区分', content_js)
        self.assertIn('竞对酒店来源: 云端历史价', content_js)
        self.assertIn('COMPETITOR_ROOM_PRICE_MESSAGE_TYPES', content_js)
        self.assertIn('requestViaExtensionBridge("competitor-room-prices", payload)', content_js)
        self.assertIn('/plugin/competitor/room-prices', content_js)
        self.assertIn('COMPETITOR_ROOM_PRICES', content_js)
        self.assertIn('fetchCompetitorRoomPricesDirect', content_js)
        self.assertIn('renderConfiguredCompetitorHotelsSummary', content_js)
        self.assertIn('setActiveBasicSection', content_js)
        self.assertIn('fliggy-ops-group-banner basic', content_js)
        self.assertIn('fliggy-ops-group-banner merchant', content_js)
        self.assertIn('按房型生成建议价，人工确认后提交', content_js)
        self.assertIn('这里默认接管飞猪平台价格页，按不同房型结合竞对价生成建议，一键回填后仍需人工确认提交。', content_js)
        self.assertIn('一键回填建议价', content_js)
        self.assertIn('DEFAULT_MERCHANT_PRICE_URL', content_js)
        self.assertIn('确认最终价并提交', content_js)
        self.assertIn('高级备用：统一目标价', content_js)
        self.assertIn('确认统一价提交', content_js)
        self.assertIn('按房型生成建议价，人工确认后提交', popup_html)
        self.assertIn('飞猪平台价格页一键回填建议价，再确认最终价。', popup_html)
        self.assertIn('https://hotel.fliggy.com/ebooking/hotelBaseInfoUv.htm#/ebk-rp/roomsVsManage', popup_html)
        self.assertIn('配置竞对房型价', popup_html)
        self.assertIn('我的价格', popup_html)
        self.assertIn('查看竞对价格', popup_html)
        self.assertIn('competitor-trend-series-select', popup_html)
        self.assertIn('竞对酒店最低价', popup_html)
        self.assertIn('生成建议价', popup_html)
        self.assertIn('打开设置', popup_html)
        self.assertIn('workspace-gate-btn', popup_html)
        self.assertIn('data-workspace-group="basic"', popup_html)
        self.assertIn('data-workspace-group="merchant"', popup_html)
        self.assertIn('data-basic-section="room-prices"', popup_html)
        self.assertIn('data-basic-section="advice"', popup_html)
        self.assertIn('data-basic-section="quick-actions"', popup_html)
        self.assertIn('页面采集、竞对配置和建议价', popup_html)
        self.assertIn('生成建议价', popup_html)
        self.assertIn('调整最终价', popup_html)
        self.assertIn('确认后提交', popup_html)
        self.assertIn('快捷动作', popup_html)
        self.assertIn('生成房型建议价', popup_html)
        self.assertIn('一键回填建议价', popup_html)
        self.assertIn('确认最终价并提交', popup_html)
        self.assertIn('高级备用：统一目标价', popup_html)
        self.assertIn('确认统一价提交', popup_html)
        self.assertIn('按当前页采集', popup_html)
        self.assertNotIn('id="page-box"', popup_html)
        self.assertNotIn('id="config-box"', popup_html)
        self.assertNotIn('读取竞对价格', popup_html)
        self.assertIn('chrome.tabs.query', popup_js)
        self.assertIn('type: "RUN_COLLECT"', popup_js)
        self.assertIn('type: "COMPETITOR_WORKFLOW_PREVIEW"', popup_js)
        self.assertIn('type: "COMPETITOR_PRICING_ADVICE_PREVIEW"', popup_js)
        self.assertIn('type: "MERCHANT_PRICING_SUBMIT_CURRENT"', popup_js)
        self.assertIn('type: "MERCHANT_UNIFORM_PRICE_SUBMIT"', popup_js)
        self.assertIn('DEFAULT_MERCHANT_PRICE_URL', popup_js)
        self.assertIn('collectConfirmedWorkflowItems', popup_js)
        self.assertIn('confirmWorkflowSubmission(confirmedItems)', popup_js)
        self.assertIn('window.confirm(buildWorkflowSubmitConfirmation(confirmedItems))', popup_js)
        self.assertIn('将按以下最终价提交到商家后台，确认后会执行真实改价。', popup_js)
        self.assertIn('confirmMerchantWorkflowSubmission(confirmedItems)', content_js)
        self.assertIn('window.confirm(buildMerchantWorkflowSubmitConfirmation(confirmedItems))', content_js)
        self.assertIn('LOCAL_MERCHANT_PRICE_ITEMS', content_js)
        self.assertIn('LOCAL_MERCHANT_PRICE_SUBMIT', content_js)
        self.assertIn('extension_local_merchant_page', content_js)
        self.assertIn('MERCHANT_PRICING_ITEMS', background_js)
        self.assertIn('DEFAULT_MERCHANT_PRICE_URL', background_js)
        self.assertIn('findLocalMerchantPortalTab', background_js)
        self.assertIn('collectLocalMerchantPriceItems', background_js)
        self.assertIn('merchant_items', background_js)
        self.assertIn('extension_current_tab', background_js)
        self.assertIn('COMPETITOR_ROOM_PRICE_MESSAGE_TYPES', popup_js)
        self.assertIn('requestCompetitorRoomPrices(payload)', popup_js)
        self.assertIn('normalizeWorkflowPreview', popup_js)
        self.assertIn('renderConfiguredCompetitorHotels', popup_js)
        self.assertIn('renderCompetitorRoomPrices', popup_js)
        self.assertIn('renderCompetitorPricingAdvice', popup_js)
        self.assertIn('seriesType: competitorTrendSeriesSelect?.value', popup_js)
        self.assertIn('getTrendSeriesTitle', popup_js)
        self.assertIn('renderCompetitorTrendSeriesDetails', popup_js)
        self.assertIn('renderTrendHotelSourceLink', popup_js)
        self.assertIn('主流房型 + 酒店', popup_js)
        self.assertIn('曲线明细：按主流房型 + 竞对酒店区分', popup_js)
        self.assertIn('主流房型: ${escapeHtml(categoryName', popup_js)
        self.assertIn('竞对酒店: ${escapeHtml(hotelName', popup_js)
        self.assertIn('竞对酒店来源: 云端历史价', popup_js)
        self.assertIn('配置链接: ${renderTrendHotelSourceLink(hotelUrl)}', popup_js)
        self.assertIn('点数 ${Number(item?.point_count', popup_js)
        self.assertIn('插件本地采集已开启', popup_js)
        self.assertIn('collectConfirmedWorkflowItems', popup_js)
        self.assertIn('renderWorkflowPreview', popup_js)
        self.assertIn('ensureWorkspaceGroupNav', popup_js)
        self.assertIn('setActiveWorkspaceGroup', popup_js)
        self.assertIn('WORKSPACE_GROUP_DEFS', popup_js)
        self.assertIn('BASIC_SECTION_DEFS', popup_js)
        self.assertIn('ensureBasicSectionNav', popup_js)
        self.assertIn('setActiveBasicSection', popup_js)
        self.assertIn('workspaceGateBtn', popup_js)
        self.assertIn('data-workspace-group', popup_js)
        self.assertNotIn('pageBox', popup_js)
        self.assertNotIn('configBox', popup_js)
        self.assertIn('previewCompetitorWorkflow', background_js)
        self.assertIn('previewCompetitorPricingAdvice', background_js)
        self.assertIn('submitUniformMerchantPricing', background_js)
        self.assertIn('COMPETITOR_WORKFLOW_PREVIEW', background_js)
        self.assertIn('COMPETITOR_PRICING_ADVICE_PREVIEW', background_js)
        self.assertIn('MERCHANT_UNIFORM_PRICE_SUBMIT', background_js)
        self.assertIn('COMPETITOR_ROOM_PRICES', background_js)
        self.assertIn('competitorHotels', background_js)
        self.assertIn('normalizeCompetitorHotels', background_js)
        self.assertIn('formatLocalDateTime', background_js)
        self.assertIn('crawlCompetitorRoomPricesViaTabs', background_js)
        self.assertIn('buildCompetitorPriceSnapshot', background_js)
        self.assertIn('buildCompetitorTrendPriceSnapshot', background_js)
        self.assertIn('buildCompetitorPriceChangeSummary', background_js)
        self.assertIn('notifyCompetitorPriceChanges', background_js)
        self.assertIn('notifyCompetitorCloudTrendRefresh', background_js)
        self.assertIn('source: "local_browser_tabs"', background_js)
        self.assertIn('crawlCompetitorRoomPricesViaTabs({', background_js)
        self.assertIn('saveResult: true', background_js)
        self.assertIn('本地竞对采集已同步', background_js)
        self.assertIn('chrome.notifications.create', background_js)
        self.assertIn('series_type: String(payload.seriesType', background_js)
        self.assertIn('/plugin/auth/login', background_js)
        self.assertIn('/plugin/competitor/hotels', background_js)
        self.assertIn('/plugin/manual-room-mappings', background_js)
        self.assertIn('/plugin/pricing/competitor-workflow-preview', background_js)
        self.assertIn('/plugin/pricing/competitor-advice-preview', background_js)
        self.assertIn('LOCAL_MERCHANT_PRICE_SUBMIT', background_js)
        self.assertIn('price_signals', background_js)
        self.assertNotIn('OPEN_PROJECT_PAGE', popup_js)
        self.assertNotIn('OPEN_PROJECT_PAGE', content_js)
        self.assertNotIn('PROJECT_PAGES', background_js)
        self.assertIn('竞对酒店配置', options_html)
        self.assertIn('我的房型映射', options_html)
        self.assertIn('账号登录', options_html)
        self.assertNotIn('后台房型映射（数据库）', options_html)
        self.assertNotIn('merchant-price-mappings', options_html)
        self.assertNotIn('refresh-merchant-mappings-btn', options_html)
        self.assertNotIn('add-merchant-mapping-btn', options_html)
        self.assertNotIn('save-merchant-mappings-btn', options_html)
        self.assertIn('auth-username-input', options_html)
        self.assertIn('auth-password-input', options_html)
        self.assertIn('auth-login-btn', options_html)
        self.assertIn('auth-refresh-btn', options_html)
        self.assertIn('auth-logout-btn', options_html)
        self.assertIn('shop-select', options_html)
        self.assertIn('当前配置', options_html)
        self.assertIn('当前页面', options_html)
        self.assertIn('current-config-box', options_html)
        self.assertIn('current-page-box', options_html)
        self.assertIn('auth-summary', options_html)
        self.assertIn('return-source-btn', options_html)
        self.assertIn('返回上一页', options_html)
        self.assertIn('competitorHotels', options_js)
        self.assertIn('renderCurrentConfigSummary', options_js)
        self.assertIn('renderCurrentPageContext', options_js)
        self.assertIn('GET_PAGE_CONTEXT', options_js)
        self.assertIn('RETURN_TO_OPTIONS_SOURCE', options_js)
        self.assertIn('OPTIONS_RETURN_TARGET_KEY', background_js)
        self.assertIn('recordOptionsReturnTarget', background_js)
        self.assertIn('returnToOptionsSource', background_js)
        self.assertIn('readCompetitorHotels', options_js)
        self.assertIn('readManualRoomMappings', options_js)
        self.assertIn('ensureAuthenticated', options_js)
        self.assertIn('type: "AUTH_LOGIN"', options_js)
        self.assertIn('type: "AUTH_SWITCH_SHOP"', options_js)
        self.assertIn('type: "AUTH_LOGOUT"', options_js)
        self.assertIn('type: "GET_AUTH_STATE"', options_js)
        self.assertIn('renderAuthSummary', options_js)
        self.assertNotIn('loadMerchantPriceMappings', options_js)
        self.assertNotIn('saveAllMerchantMappings', options_js)
        self.assertNotIn('appendMerchantMappingRow', options_js)
        self.assertNotIn('merchantMappingList', options_js)
        self.assertIn('extractPriceSignals', page_context_js)
        self.assertIn('pickBestPrice', page_context_js)
        self.assertIn('price_text', page_context_js)
        self.assertIn('collectTargetHintCandidateNodes', page_context_js)
        self.assertIn('resolveCandidateContainerFromHint', page_context_js)
        self.assertIn('collectAllPages: false', popup_js)
        self.assertIn('targetHotelNames: manualTargets', popup_js)
        self.assertIn('collectAllPages: false', content_js)
        self.assertIn('targetHotelNames: manualTargets', content_js)
        self.assertNotIn('data-action="prices"', content_js)


if __name__ == '__main__':
    unittest.main()




